stages:
  - test
  - build
  - deploy
test:
  stage: test
  script: echo "Running tests“
  tags: 
    - docker-runner

build:
  stage: build
  script: echo "Building the app“
  tags: 
    - docker-runner
deploy_staging:
  stage: deploy
  script: 
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
     - master
  tags:
     - docker-runner
